# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'AppAuthExample' do
  pod 'React', :path => '../node_modules/react-native'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'GLog', :podspec => '../node_modules/react-native/third-party-podspecs/GLog.podspec'
  pod 'RNAppAuth', :path => '../../ios/'
end
